import { initializeApp } from "firebase/app";
import { getFirestore, doc, onSnapshot, setDoc, updateDoc } from "firebase/firestore";
import firebaseConfig from "../firebase-applet-config.json";

// Initialize Firebase using the configuration generated by standard AI Studio setup
const app = initializeApp(firebaseConfig);
export const db = getFirestore(app, firebaseConfig.firestoreDatabaseId);

// Collection and Document references for real-time state synchronization
export const STATE_COLLECTION = "fedelibapam_data";
export const STATE_DOC_ID = "main_state";

export const stateDocRef = doc(db, STATE_COLLECTION, STATE_DOC_ID);
